import type { Metadata } from "next";
import { Roboto, Comic_Neue } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-app",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} font-sans antialiased h-screen`}>
        <Navigation />
        <main className="h-[calc(100dvh-110px)] min-h-0">{children}</main>
      </body>
    </html>
  );
}
